;; Package --- summary:
;; additonal configuration included in ~/.emacs.d/config.org
;; Commentary:

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

;; Define config target
(setq-default user-emacs-directory (file-truename "~/.emacs.d/"))

;; Load settings
(org-babel-load-file (expand-file-name (concat user-emacs-directory "config.org")))

;; Settings that are auto-generated by emacs go here
(setq custom-file (expand-file-name (concat user-emacs-directory "custom.el")))
(when (file-exists-p custom-file)
  (load custom-file))

;; .emacs ends here
